#!/bin/bash
set -x

jBLUiR='java -jar BLUiR.jar '
proj=/home/johnjmar/uni/spring16/final_proj
bugRepo=${proj}/ExampleProject/SWTBugRepository.xml 
srcRepo=${proj}/ExampleProject/swt/src/org
outDir=${proj}/testRunOut

cd BLUiR

#create query from XML Bug Repository
$jBLUiR -task='createquery' \
 -bugRepoLocation=${bugRepo} \
 -queryFilePath=${outDir}/query

#construct a structured document collection from source code files 
$jBLUiR -task='createdocs' \
 -codeLocation=${srcRepo} \
 -docLocation=${outDir}/docs

#index document collection
$jBLUiR -task='index' \
 -indexLocation=${outDir}/index \
 -docLocation=${outDir}/docs

#perform retrieval to identify buggy files
$jBLUiR -task='retrieve' \
 -queryFilePath=${outDir}/query \
 -indexLocation=${outDir}/index \
 -resultPath=${outDir}/results.txt
